### ISSUE TITLE
standup crashes if there are VPC instances in the EC2

### ISSUE THREAD

**Issue by antlypls** [creative-co/standup#13]
standup crashes because vpc instances have empty security group (it uses vpc security groups).

```
/Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:76:in `build_info': undefined method `item' for nil:NilClass (NoMethodError)
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:17:in `block (2 levels) in list'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:16:in `each'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:16:in `block in list'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:15:in `each'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:15:in `list'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/ec2/instance.rb:27:in `group_running'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/node.rb:24:in `instance'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/scripts/node.rb:11:in `instance'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/scripts/ec2.rb:34:in `ensure_instance'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/scripts/ec2.rb:7:in `run'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/scripts/setup.rb:9:in `block in run'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/scripts/setup.rb:7:in `each'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/scripts/setup.rb:7:in `run'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/node.rb:19:in `run_script'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/scripts/node.rb:43:in `block in run_on_nodes'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/scripts/node.rb:43:in `each'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/scripts/node.rb:43:in `run_on_nodes'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup/scripts/node.rb:39:in `execute'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/lib/standup.rb:101:in `run_from_command_line'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/standup-0.6.5/bin/standup:10:in `<top (required)>'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bin/standup:19:in `load'
    from /Users/anatoliy/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/bin/standup:19:in `<main>'
```

**Comment by Flamefork** [comment]
@antlypls please check this..
