### ISSUE TITLE
undefined method `__file__' for #<Proc> using vanilla ruby

### ISSUE THREAD

**Issue by Flamefork** [creative-co/standup#4]
```
> rvm use 1.8.7
Using /Users/flamefork/.rvm/gems/ruby-1.8.7-p302
> standup status
/Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:46:in `script': undefined method `__file__' for #<Proc:0x101ea7660> (NoMethodError)
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/scripts/allocate_ip.rb:1
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:38:in `load'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:38:in `scripts'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:35:in `foreach'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:35:in `scripts'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:34:in `each'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/lib/standup.rb:34:in `scripts'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/bin/standup:18:in `cloaker_'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/trollop-1.16.2/lib/trollop.rb:82:in `call'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/trollop-1.16.2/lib/trollop.rb:82:in `initialize'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/bin/standup:7:in `new'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/gems/standup-0.3.13/bin/standup:7
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/bin/standup:19:in `load'
    from /Users/flamefork/.rvm/gems/ruby-1.8.7-p302/bin/standup:19
```

**Comment by Flamefork** [comment]
Closed by 620962e4e654480693bc6afa7c83df96cfa05004 : undefined method `**file**&#39; for #&lt;Proc&gt; using vanilla ruby
